export const QUESTIONS = {
  icebreaker: [
    "Which player do you think is the most fun to be around?",
    "Who has the best fashion sense in the group?",
    "Who is most likely to cry during a sad movie?",
    "Who do you think is the best-dressed here?",
    "Who is the least likely to be up for a spontaneous plan?",
    "Who is most likely to become a social media influencer?",
    "Can you guess who here hasn't read a book since high school?",
    "Which player has the best sense of humor?",
    "Who tells the best dad jokes?",
    "Which person here would be the best on Big Brother?",
    "Who do you think has the most controversial food opinions?",
    "Who is most likely to volunteer as tribute in the Hunger Games?",
    "Who in this room do you trust the most?",
    "Who always has the best advice during a crisis?",
    "Who is the unsung soldier holding the group together?",
    "Which member in the group has grown the most in the past year?",
    "Who do you think will be the most successful in 10 years?",
    "Who here deserves more appreciation and recognition from the group?",
    "Which member do you think has a secret LEGO obsession?",
    "Who is most likely to adopt 10 pets in the future?",
    "Who has the most creative imagination?",
    "Who is most likely to get excited over an animated film?",
    "Which member in the group is the handiest at building things?",
    "Which player gives the cuddliest hugs?",
    "Who amongst the group do you think is the luckiest in love?",
    "Which member are you secretly very afraid of?",
    "Who sitting here is likely to get jealous if you go out with a new friend?",
    "Which player are you least likely to call during an emergency?",
    "Who is most likely to embarrass a friend in public?",
    "Pick someone in the group who is most likely to have a weird phobia",
    "Who do you think deserves a better romantic partner?",
  ],
  funny: [
    "Who is most likely to get lost even with a GPS?",
    "Who's most likely to be late for a plan because they stopped to pet a dog?",
    "Who do you think has the most embarrassing Spotify playlists?",
    "Who's most likely to get blocked by a celebrity on social media?",
    "Who is guilty of never matching their socks?",
    "Who should have a reality TV show based on their life?",
    "Who would accidentally send a text to the wrong person?",
    "Who do you think has the highest alcohol tolerance?",
    "Which member has the best dance moves when drunk?",
    "Who do you think is the life of the party?",
    "Which player throws the best parties?",
    "Who is most likely to start a conga line?",
    "Which player in the group is most likely to have the sickest playlist?",
    "Who is most likely to be the party pooper?",
    "Who is most likely to finish all the party snacks when no one's watching?",
    "Who can't cook to save their life?",
    "Who's the gossip monger of the group?",
    "Who is the worst texter present here?",
    "Who is most likely to get an embarrassing tattoo?",
    "Which player is pursuing the wrong career?",
    "Who should try their hand at stand-up comedy?",
    "Who in the group has the dirtiest sense of humor?",
    "Who has the best blackout story?",
    "Who is most likely to skip dinner and dive right into eating dessert?",
    "Who is most likely to get arrested?",
    "Who is the worst gift-giver in the group?",
    "Who makes the least money in the group?",
    "Which player is the stingiest amongst the group?",
    "Who's the flakiest member in the group?",
    "Who is most likely to be rude to the wait staff at a restaurant?",
    "Who is most likely to arrive two hours late to any event?",
    "Who do you think needs to shower more often?",
    "Who's the worst at driving?",
    "Who has the worst road rage in the group?",
    "Who is the biggest prude in the group?",
    "Who here tends to get overly competitive?",
    "Who do you think is the fakest on their socials?",
    "Out of all the players in the group, who's the best liar?",
    "Who talks about people behind their backs the most?",
    "Who had the craziest first date experience?",
    "If you could switch lives with someone here for a day, who would it be?",
    "Who is most likely to get arrested for indecent behavior?",
    "Who would have the funniest drunk photos?",
    "Which player is most likely to suggest the after-parties?",
    "Which player is most likely to get chatty with strangers while waiting in line for the bathroom?",
    "Who would make the best superhero?",
    "Who has the best excuses for getting out of trouble?",
    "Who's most likely to win in a game of tennis?",
    "Who makes the worst babysitter?",
  ],
  spicy: [
    "Which player do you think would be the best kisser?",
    "Who do you think is most likely to have a one-night stand?",
    "Who is most likely to kiss a stranger?",
    "Who do you think is the most scandalous texter?",
    "Who has the most effortless flirting skills?",
    "Who is most likely to go skinny dipping?",
    "Who do you think is most likely to gaslight their partner?",
    "Which member in the group has cheated or is most likely to cheat on their partner?",
    "Who do you think is most likely to ghost someone they've been seeing?",
    "Who do you think is the most emotionally unavailable member?",
    "Pick one member in the group whom you would most likely have a crush on.",
    "Who is least likely to get married?",
    "Which player would you never want to go on a date with?",
    "If you had to pick, who do you think is most likely to betray a friend for personal gain?",
    "Which member would rat their friend out during an interrogation?",
    "Who is most likely to get plastic surgery and lie about it?",
    "Who is most likely to date more than one person at a time?",
    "Who do you think goes the most days without showering?",
    "If you had to, who would you kick out of the group?",
    "Who would you call to help you bury a body?",
    "Who here is the biggest people-pleaser?",
    "Who do you think has the most self-doubt?",
    "Which player is most likely to get back with their ex?",
    "Which player would throw hands instead of talking things out?",
    "Who do you think would be the worst roommate?",
    "Which player do you think would be the least talented in bed?",
    "Which player is most likely to contract an STD?",
    "Who in this circle do you want to sleep with?",
    "Who do you think has the highest body count?",
    "Which member do you think was last to lose their virginity?",
    "Which player do you believe isn't ready for a relationship?",
    "Who do you think would have the highest success after making the first move?",
    "Who do you think would have the least success in a long-term relationship?",
    "Who is most likely to pay for excess luggage before a flight?",
  ],
  extreme: [
    "Who is most likely to ghost someone?",
    "Who is most likely to stand someone up on a date?",
    "Who is most likely to send an inappropriate text to someone when they are drunk?",
    "Who has had the most one-night stands?",
    "Who would most likely have a secret lovechild with someone famous?",
    "Who is most likely to flirt with a teacher?",
    "Who would flirt their way out of a speeding ticket?",
    "Who would hook up with someone older than their parents?",
    "Who is most likely to get caught in the act by someone?",
    "Who is most likely to hookup with an ex?",
    "Who is most likely to have a weird fetish?",
    "Who is most likely to email their boss something scandalous by mistake?",
    "Who is most likely to send a naughty text to a friend by accident?",
    "Who has done the walk of shame?",
    "Who is the biggest tease?",
    "Who has ever lied to someone to try to impress them?",
    "Who is most likely to do the deed outside in nature?",
    "Who would fall asleep on a first date?",
    "Who would have a secret workplace romance?",
    "Who would kiss a stranger during a fun night out on the town?",
    "Who would be caught watching something steamy?",
    "Who has the most questionable Google history?",
    "Who is the most awkward when it comes to hooking up?",
    "Who is most likely not to know the name of someone they hook up with?",
    "Who has the steamiest fantasy?",
    "Who's most likely to join the Mile High Club?",
    "Who has played the most strip poker?",
    "Who brushes their teeth the least?",
    "Who is the best at talking dirty?",
    "Who has a go-to hookup playlist on their phone?",
    "Who reads the most smut?",
    "Who would be the best sugar momma or sugar daddy?",
    "Who likely walks around naked in their home the most?",
    "Who has sent the spiciest texts?",
    "Who would have a foot fetish?",
    "Who would probably make an OnlyFans account and excel at it?",
    "Who would most likely stalk an ex's Instagram?",
    "Who would makeout with a stranger when they are on vacation?",
    "Who would most likely hook up in a hot tub?",
    "Who would most likely leave their number on a restaurant receipt?",
    "Who would most likely have a fake Instagram account?",
    "Who's most likely to date someone just to get free drinks?",
    "Who has given the most hickies?",
    "Who would most likely like an ex's picture by mistake?",
    "Who has most likely had a spicy daydream about someone in this room?",
    "Who would get a tattoo in a risqué place?",
    "Who would probably lie about how many people they have been with?",
    "Who would give the best striptease?",
    "Who is probably the worst kisser?",
    "Who would be attracted to a friend's sibling?",
    "Who is most likely to lie about their age to someone they like?",
    "Who is most likely to go home with someone they meet at the bar?",
    "Who would get canceled first if they had their own podcast?",
    "Who posts the most thirst traps online?",
    "Who would slide into a celeb's DMs?",
    "Who would likely send a text to someone saying, 'Wanna come over?'",
    "Who would kiss their ex if they ran into them?",
    "Who would accidentally leak their own nudes?",
    "Who has likely snuck into their crush's home before?",
    "Who would likely go through their partner's phone when they are asleep?",
    "Who would most likely get blocked by an ex?",
    "Who has the wildest hookup story?",
    "Who would most likely catfish someone online?",
    "Who has the spiciest relationship?",
    "Who is the least pure?",
    "Who has the dirtiest mind?",
    "Who is the sexiest person here?",
    "Who would make out on the first date?",
    "Who has the best figure here?",
    "Who owns the sexiest underwear?",
    "Who has the best booty here?",
    "Who has the most kissable lips here?",
    "Who probably never got the birds and bees talk as a teenager?",
    "Who is the most vanilla person here?",
    "Who has made out with more than one person in one night?",
    "Who would send the same message to a dozen people on Tinder?",
    "Who here pretends they're shy but definitely aren't in bed?",
    "Who here definitely knows how to make someone blush?",
    "Who here would make eye contact feel illegal?",
    "Who is most likely a mama's boy or girl still?",
    "Who is the most untrustworthy person here?",
    "Who is most likely to try to steal a friend's partner?",
    "Who has the worst hygiene?",
    "Who has the ugliest exes?",
    "Who is most likely to be on a dating show?",
    "Who would be the biggest show-off in bed?",
    "Who has the hottest mom?",
    "Who has hooked up the least?",
    "Who would you not want to sleep with here?",
    "Who is most likely to get a stranger pregnant?",
    "Who has the worst go-to pickup line?",
    "Who is most likely going commando right now?",
    "Who most likely had a spicy dream last night?",
    "Who has the most out-there hall pass?",
    "Who has the hottest dad?",
    "Who is most likely to go streaking?",
    "Which person could probably actually get away with murder?",
    "Who is the biggest walking red flag here?",
    "Who is likely to land in jail?",
    "Who's most likely to flake on plans?",
    "Who is the biggest prude?",
    "Who has the craziest blackout story?",
    "Who would be the worst parent?",
    "Who wouldn't shower after hooking up with someone?",
    "Who is the creepiest person here?",
    "Who most likely flirts with themselves in the mirror?",
    "Who would kiss a total stranger on a dare?",
    "Who has the juiciest secret?",
    "If everyone were in danger, who would you save first?",
    "If you had to hook up with someone in the group, who would it be?",
    "Who would you least trust alone with your crush?",
    "Who here would accidentally lead someone on?",
    "Who here would be the most dangerous crush to have?",
    "Who would be the most dangerous person to sit next to after midnight?",
    "Who here would be the most fun to flirt with at a party?",
    "Who would be the most fun to flirt with, but the riskiest to like?",
    "If you had to pick someone, who would you go on a date with?",
    "Who here gives off the biggest 'heartbreaker' vibe?",
    "Who here gives off the strongest 'date me' energy?",
    "Who do you think gets the most attention without even trying?",
    "Who would be the hardest to forget after meeting once?",
    "Who here probably knows exactly how attractive they are?",
    "Who here probably has the best 'accidental rizz'?",
    "Who here would be the hardest to say no to?",
    "Who here would be the best in a make-out scene in a rom-com?",
    "Who would likely get canceled on a reality show?",
    "Who has the worst fashion sense when it comes to undergarments?",
    "Who is most likely to blackmail someone?",
    "Who would get a tattoo of their partner's name and regret it later?",
    "Who has the most unusual talent?",
    "Who makes the least amount of money?",
    "Who has likely wet the bed as an adult?",
    "Who here probably has the most unread DMs?",
    "Who most likely would lie and tell their parents they are dating someone when they aren't?",
    "Who would you not trust with your passwords?",
    "Who would most likely kidnap their crush?",
    "Who is most likely to get punched in the face?",
    "Who is most likely to go to a nudist beach and strip?",
    "Who is most likely to have a really dark past?",
    "Who here would steal all the attention without trying?",
    "Who could make someone rethink boundaries?",
    "Who would make a casual hug feel electric?",
    "Who has likely peeped at someone when they weren't supposed to?",
    "Who here could turn small touches into sexual tension?",
    "Who here could turn a casual joke into flirtation?",
    "Who would likely have overheard a secret and used it to their advantage?",
    "Who would probably wait until after their birthday to break up with someone to get a gift?",
    "Who usually crushes on people out of their league?",
    "Who do you think has the most secret tattoos?",
    "Who do you think has the most skeletons in their closet?",
    "Who would be most likely to have a stalker?",
    "Who do you think is most likely to have a secret marriage?",
    "Who probably has the most shocking romantic history?",
    "Who most likely has the most promiscuous past?",
    "Who probably has the spiciest Tinder profile?",
    "Who here do you think has the most explicit sexting history?",
    "Who likely has the most scandalous romantic getaway stories?",
    "Who do you think has the most risqué social media presence?",
    "Out of everyone here, who would have a secret romance with their neighbor?",
    "Who has the most thirst trap pics on their dating profile?",
    "Who is most likely to have a secret desire to be a stripper?",
    "In another life, who would have multiple husbands or wives at once?",
    "Who would accidentally join a cult?",
    "Who would get fired for sending a drunk email to their boss?",
    "Who would clog the toilet at someone's house and not tell anyone?",
    "Who would randomly be attracted to a cartoon character?",
    "Who do you think has never been to a strip club?",
    "Who would throw the worst party?",
    "Who show up drunk on their own wedding day?",
    "Who would take a prank way too far?",
    "Who would give the worst advice?",
    "Who would you never put down as your emergency contact in this group?",
    "Who would you not trust to shoot a bottle off your head?",
    "Who has the worst commitment issues?",
    "Who is the most immature?",
  ],
};

export const CATEGORY_META = {
  icebreaker: { label: "Icebreaker & Friendship", desc: "Safe, wholesome, easy for anyone", color: "from-sky-600 to-cyan-500" },
  funny: { label: "Funny & Party", desc: "Laughs, roasts & party chaos", color: "from-amber-600 to-orange-500" },
  spicy: { label: "Call-Out", desc: "Juicy, dramatic, boundary-pushing", color: "from-pink-600 to-rose-500" },
  extreme: { label: "Spicy", desc: "Explicit, dirty, adults only", color: "from-red-700 to-orange-600" },
};

export const shuffle = (arr) => [...arr].sort(() => Math.random() - 0.5);